# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [10]:
import numpy as np

2. Create a null vector of size 10 

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [12]:
array = np.arange(10,50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [13]:
#np.shape(array)
array.shape

(40,)

5. Print the type of the previous array in question 3

In [14]:
array.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [15]:
print(np.__version__)
print(np.show_config())

1.19.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mudda/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mudda/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mudda/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mudda/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mudda/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mudda/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mudda/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/mudda/Anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [16]:
array.ndim

1

8. Create a boolean array with all the True values

In [17]:
boolarray = np.array(True)

9. Create a two dimensional array




In [19]:
array2d = np.array([[1,2,3],[4,5,6]])
print(array2d)
print(array2d.ndim)

[[1 2 3]
 [4 5 6]]
2


10. Create a three dimensional array



In [20]:
array3d = np.zeros([3,3,3])
print(array3d)
print(array3d.ndim)

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [21]:
np.flip(array)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [22]:
arr = np.zeros(10); arr[5] = 1; arr
#(np.arange(10) == 4).astype(int)

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [23]:
arridnt = np.eye(3);
arridnt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [25]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1 * arr2
#np.multiply(arr1, arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [26]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr1 > arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [133]:
arr = np.arange(10)
#condition = (arr % 2 == 1)
#print (condition)
#arrodd = arr[condition]
arrodd = arr[arr % 2 == 1]
print(arr)
print(arrodd)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [79]:
arr[arr%2 == 1] = -1
arr

#arrodd[:] = -1
#print(arrodd)
#print(arr)....... does not work... why?... because boolean indexing?

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [85]:
arr = np.arange(10)
#arr[[5,6,7,8]] = 12
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [111]:
arroneszeros = np.zeros([5,5])
arroneszeros[0:,0] = 1
arroneszeros[0,0:] = 1
arroneszeros[0:,-1] = 1
arroneszeros[-1,0:] = 1
arroneszeros

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [116]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
#arr2d[1,1] = 12
arr2d[arr2d[:] ==5] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [119]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [145]:
arr2d = np.arange(9).reshape(3,3)
print(arr2d[[0]])

print(arr2d[0,])

#arr2d = arr2d[1:,]
#print(arr2d)

[[0 1 2]]
[0 1 2]


In [146]:
arr2d = np.arange(9).reshape(3,3)
print(arr2d[[1],[1]])

print(arr2d[1,1])

[4]
4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [149]:
arr2d = np.arange(9).reshape(3,3)
print(arr2d)
arr2d[0:2,2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [155]:
arrrand = np.random.rand(10, 10)
print(arrrand)
print(arrrand.min())
print(arrrand[:].min())
print(arrrand.max())
print(arrrand[:].max())

[[2.48109743e-01 7.93207120e-01 3.87005400e-01 4.05905522e-01
  6.69778231e-01 3.86230856e-01 1.96978802e-01 4.77284973e-01
  8.92041476e-01 8.13676743e-01]
 [2.96582717e-01 3.40721258e-01 7.79896903e-01 7.03562698e-01
  9.94170670e-02 9.37171019e-01 3.72994339e-01 1.56017333e-01
  9.42055031e-01 6.17106364e-01]
 [3.59736788e-01 3.44195590e-01 1.82959470e-01 8.58149996e-01
  9.08112356e-01 8.60081479e-01 6.47742350e-02 1.07341332e-01
  6.66168640e-01 1.66712485e-01]
 [8.82856470e-01 7.93361961e-01 4.20121096e-01 7.25610689e-01
  8.24086058e-02 1.66831418e-01 4.01064154e-01 1.05715535e-01
  4.13153030e-01 2.35389658e-02]
 [1.15711884e-01 4.63980803e-02 6.08891550e-01 5.13936072e-01
  9.69881344e-01 4.61853945e-01 2.47468332e-01 2.71482769e-01
  4.62563605e-02 6.41399003e-01]
 [2.49287317e-01 5.04466569e-01 4.35186222e-01 4.28576237e-01
  7.68291528e-01 8.65780226e-01 2.83011958e-01 2.88701498e-01
  8.11548389e-01 7.29110102e-01]
 [3.00728219e-01 9.95881047e-01 9.14973518e-02 4.46440787e

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [224]:
a = np.array([1,2,3,2,3,4,3,4,5,6]); b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a); print(b)
print(a == b)
abcom = a[a == b]
print(abcom)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
[False  True False  True False  True False  True False False]
[2 2 4 4]
++++


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [167]:
a = np.array([1,2,3,2,3,4,3,4,5,6]); b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a); print(b)
np.arange(10)[a == b]

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


array([1, 3, 5, 7])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [181]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']);data = np.random.randn(7, 4)
print(data)
data[names == 'Will']

[[-0.42386187 -0.49448567  0.22714496 -0.05486963]
 [ 0.66812267  1.15274393 -0.787727   -1.12649703]
 [-0.67232571 -0.53964735 -0.72276938 -0.54838813]
 [ 1.06459094 -1.25948947  0.83782791 -0.70810998]
 [ 0.60047719 -0.04959289  1.92239226 -0.4966901 ]
 [-1.5209531   0.91430723 -0.45419994  0.03826016]
 [ 1.74998298 -1.06821107  0.67511228 -0.35879729]]


array([[-0.67232571, -0.53964735, -0.72276938, -0.54838813],
       [ 0.60047719, -0.04959289,  1.92239226, -0.4966901 ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [193]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']); data = np.random.randn(7, 4)
print(data)
print('+++')
print(data[(names!= 'Will') & (names != 'Joe')])
#print(data[~((names == 'Will') | (names == 'Joe'))])

[[-0.58155742  1.43699768  0.34527675 -0.59621529]
 [ 0.06070568 -0.02654764  1.42623704 -0.71837265]
 [ 1.06343102  0.3007353   1.48942086  0.6290972 ]
 [ 1.02545536 -0.04362326  0.65028202  0.10201473]
 [-0.54694234  1.54890204 -0.56209652 -1.10706593]
 [-1.23525705  1.61793145  0.71099315 -0.48539504]
 [ 1.6325857  -1.22885804 -1.48019529 -0.15064943]]
+++
[[-0.58155742  1.43699768  0.34527675 -0.59621529]
 [ 1.02545536 -0.04362326  0.65028202  0.10201473]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [194]:
np.random.uniform(1,15, size=(5,3))

array([[ 2.49886575, 14.40686867,  5.81847391],
       [ 8.30964688,  6.37504888, 12.65575346],
       [ 8.27327509,  6.56764777,  3.08139507],
       [ 4.87291875,  2.31011649, 10.82830599],
       [ 6.78559324,  8.65670364,  9.41033678]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [225]:
arr2dec = np.random.uniform(1,16, size=(2,2,4))
arr2dec

array([[[ 2.06755619, 14.36023793, 15.27841789,  8.53767931],
        [13.04351398,  3.68197589, 10.79338699,  2.96513297]],

       [[ 7.39444822,  2.22271833,  5.02352257,  6.34387894],
        [15.22257896, 15.92971256, 12.65815076, 15.28336815]]])

33. Swap axes of the array you created in Question 32

In [198]:
arr2dec.swapaxes(0,1)

array([[[7.05637665, 9.17380887, 7.71634986, 5.95563979],
        [8.43252722, 6.1836547 , 8.05463695, 8.99086184]],

       [[9.97131867, 7.93972839, 6.03287461, 9.96294048],
        [7.53571264, 7.83564821, 5.77467014, 9.32296384]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [230]:
arrsqrt = np.sqrt(np.random.randint(0,3,10))
print(arrsqrt)

np.where(arrsqrt < 0.5, 0, arrsqrt)


[1.41421356 1.41421356 0.         1.41421356 1.         0.
 1.41421356 0.         1.         1.41421356]


array([1.41421356, 1.41421356, 0.        , 1.41421356, 1.        ,
       0.        , 1.41421356, 0.        , 1.        , 1.41421356])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [235]:
arrrand1 = np.random.rand(12)
print(arrrand1)
print('+++')
arrrand2 = np.random.rand(12)
print(arrrand2)
print('++++')
np.where (arrrand1 > arrrand2, arrrand1, arrrand2)

[0.35113863 0.06294542 0.77013707 0.47166774 0.00931644 0.60258017
 0.97525499 0.61021634 0.54851369 0.42960168 0.39529713 0.7279996 ]
+++
[0.23313834 0.36488094 0.91804572 0.34942553 0.79916016 0.10954657
 0.17496176 0.0277498  0.77130165 0.83554789 0.03689658 0.92956575]
++++


array([0.35113863, 0.36488094, 0.91804572, 0.47166774, 0.79916016,
       0.60258017, 0.97525499, 0.61021634, 0.77130165, 0.83554789,
       0.39529713, 0.92956575])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [252]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
print(np.sort(names))

['Bob' 'Joe' 'Will']
['Bob' 'Bob' 'Joe' 'Joe' 'Joe' 'Will' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


40. Generate a matrix of 20 random values and find its cumulative sum